server {
    listen 80;
    server_name localhost;

    # 도커 내부 DNS 서버 지정 (필수)
    resolver 127.0.0.11;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
       resolver 127.0.0.11 valid=30s;
    
        set $backend_url "http://semi-backend:9999";
        proxy_pass $backend_url;
    }

    location ~* ^/(api|undefined)/(.*) {
        rewrite ^/(api|undefined)/(.*) /$2 break;
        
        # 변수 처리를 통해 host not found 에러 방지
        set $backend "semi-backend";
        proxy_pass http://$backend:9999;
        
        proxy_set_header Host $host;
    }
}
