--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-12-2026   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence
--------------------------------------------------------
CREATE SEQUENCE TEAM1_DB.ADMIN_LOG_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 221 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.ALARM_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 161 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.ATTENDANCE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 74 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.BOARDTEST_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 21 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.BOARD_FILE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.BOARD_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 21 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CAMPAIGN_NOTICE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 181 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CAMPAIGN_NO_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 281 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CAMPAIGN_PARTICIPANCE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 181 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CAMPAIGN_UPDATE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 101 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CART_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 181 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CO2_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 101 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.CONTRIBUTION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 272 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.DONATION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.FAQ_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 81 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.KEYWORD_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 21 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.LOG_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1661 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.MEMBER_LOG_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.MISSION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.NOTICE_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 181 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.POINT_DONATION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 141 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.POINT_NO_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 91 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.POINT_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 323 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.QNA_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 221 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.REGION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.REPORT_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 221 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.SEQ_BOARD_COMMENT_NO MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 143 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.SEQ_DONATION_NO MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM1_DB.USER_MISSION_SEQ MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 516 NOCACHE NOCYCLE;

--------------------------------------------------------
--  DDL for Table ADMIN_LOG_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.ADMIN_LOG_TBL 
(
    LOG_NO INT, 
    ADMIN_ID VARCHAR(20), 
    LOG_TARGET_ID VARCHAR(20), 
    LOG_RESULT VARCHAR(100), 
    LOG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    LOG_REASON VARCHAR(600), 
    REPORT_NO INT, 
    LOG_ACTION VARCHAR(20)
);

--------------------------------------------------------
--  DDL for Table ALARM_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.ALARM_TBL 
(
    ALARM_NO INT, 
    MEMBER_ID VARCHAR(20), 
    ALARM_KIND INT, 
    ALARM_CONTENT VARCHAR(1000), 
    ALARM_DATA VARCHAR(2000), 
    ALARM_CHECK INT DEFAULT 0, 
    ALARM_TIME DATETIME DEFAULT CURRENT_TIMESTAMP, 
    ALARM_DEL INT DEFAULT 1, 
    POINT_NO INT
);

--------------------------------------------------------
--  DDL for Table ATTENDANCE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.ATTENDANCE_TBL 
(
    ATTENDANCE_NO INT, 
    MEMBER_ID VARCHAR(20), 
    ATTEND_YMD DATETIME, 
    REWARD_POINT INT DEFAULT 0
);

--------------------------------------------------------
--  DDL for Table BOARD_COMMENT_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.BOARD_COMMENT_TBL 
(
    BOARD_COMMENT_NO INT, 
    BOARD_COMMENT_WRITER VARCHAR(20), 
    BOARD_NO INT, 
    BOARD_COMMENT_CONTENT VARCHAR(1000), 
    BOARD_COMMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP, 
    MEMBER_NICKNAME VARCHAR(30), 
    PARENT_COMMENT_NO INT, 
    COMMENT_GROUP INT, 
    COMMENT_DEPTH INT DEFAULT 0, 
    IS_SECRET CHAR(1) DEFAULT 'N', 
    BOARD_COMMENT_STATUS INT DEFAULT 0
);

--------------------------------------------------------
--  DDL for Table BOARD_FILE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.BOARD_FILE_TBL 
(
    FILE_NO INT, 
    BOARD_NO INT, 
    MEMBER_ID VARCHAR(20), 
    BOARD_FILE_NAME VARCHAR(300), 
    BOARD_FILE_PATH VARCHAR(300)
);

--------------------------------------------------------
--  DDL for Table BOARD_LIKE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.BOARD_LIKE_TBL 
(
    BOARD_NO INT, 
    MEMBER_ID VARCHAR(20)
);

--------------------------------------------------------
--  DDL for Table BOARD_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.BOARD_TBL 
(
    BOARD_NO INT NOT NULL AUTO_INCREMENT, 
    WRITER_ID VARCHAR(20), 
    BOARD_TITLE VARCHAR(1000), 
    BOARD_CONTENT VARCHAR(4000), 
    BOARD_THUMB VARCHAR(300), 
    BOARD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    MEMBER_NICKNAME VARCHAR(30), 
    BOARD_STATUS INT DEFAULT 0, 
    BOARD_LAT DOUBLE, 
    BOARD_LNG DOUBLE, 
    READ_COUNT INT DEFAULT 0, 
    CTPV VARCHAR(50), 
    SGG VARCHAR(50), 
    UPDATED_AT DATETIME, 
    ADDR VARCHAR(100),
    PRIMARY KEY (BOARD_NO)
);

--------------------------------------------------------
--  DDL for Table CAMPAIGN_EXILE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CAMPAIGN_EXILE_TBL 
(
    MEMBER_ID VARCHAR(30), 
    CAMPAIGN_NO INT, 
    CAMPAIGN_EXILE_REASON VARCHAR(1000)
);

--------------------------------------------------------
--  DDL for Table CAMPAIGN_MEMBER_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CAMPAIGN_MEMBER_TBL 
(
    MEMBER_ID VARCHAR(30), 
    CAMPAIGN_NO INT
);

--------------------------------------------------------
--  DDL for Table CAMPAIGN_NOTICE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CAMPAIGN_NOTICE_TBL 
(
    CAMPAIGN_NOTICE_NO INT, 
    CAMPAIGN_NOTICE_TITLE VARCHAR(1000), 
    CAMPAIGN_NOTICE_CONTENT VARCHAR(2000), 
    CAMPAIGN_NOTICE_WRITER VARCHAR(30), 
    CAMPAIGN_NO INT, 
    CAMPAIGN_NOTICE_DATE DATETIME
);

--------------------------------------------------------
--  DDL for Table CAMPAIGN_PARTICIPANCE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CAMPAIGN_PARTICIPANCE_TBL 
(
    CAMPAIGN_PARTICIPANCE_NO INT, 
    CAMPAIGN_THUMB VARCHAR(300), 
    CAMPAIGN_MEMO VARCHAR(500), 
    CAMPAIGN_NO INT, 
    CAMPAIGN_MEMO_UPLOAD_DATE DATETIME, 
    CAMPAIGN_EXPIRE_DATE DATETIME, 
    MEMBER_ID VARCHAR(20)
);

--------------------------------------------------------
--  DDL for Table CAMPAIGN_UPDATE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CAMPAIGN_UPDATE_TBL 
(
    CAMPAIGN_UPDATE_NO INT, 
    CAMPAIGN_TITLE VARCHAR(1000), 
    CAMPAIGN_EXPLANATION VARCHAR(2000), 
    CAMPAIGN_GOAL_MEMBER INT, 
    CAMPAIGN_NO INT
);

--------------------------------------------------------
--  DDL for Table CARBON_ELE_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CARBON_ELE_TBL 
(
    CTPVSGG_ID CHAR(8), 
    CARBON_ELE_JAN INT, 
    CARBON_ELE_FEB INT, 
    CARBON_ELE_MAR INT, 
    CARBON_ELE_APR INT, 
    CARBON_ELE_MAY INT, 
    CARBON_ELE_JUN INT, 
    CARBON_ELE_JUL INT, 
    CARBON_ELE_AUG INT, 
    CARBON_ELE_SEP INT, 
    CARBON_ELE_OCT INT, 
    CARBON_ELE_NOV INT, 
    CARBON_ELE_DEC INT, 
    CARBON_ELE_TOT INT
);

--------------------------------------------------------
--  DDL for Table CARBON_GAS_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CARBON_GAS_TBL 
(
    CTPVSGG_ID CHAR(8), 
    CARBON_GAS_JAN INT, 
    CARBON_GAS_FEB INT, 
    CARBON_GAS_MAR INT, 
    CARBON_GAS_APR INT, 
    CARBON_GAS_MAY INT, 
    CARBON_GAS_JUN INT, 
    CARBON_GAS_JUL INT, 
    CARBON_GAS_AUG INT, 
    CARBON_GAS_SEP INT, 
    CARBON_GAS_OCT INT, 
    CARBON_GAS_NOV INT, 
    CARBON_GAS_DEC INT, 
    CARBON_GAS_TOT INT
);

--------------------------------------------------------
--  DDL for Table CARBON_HEAT_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CARBON_HEAT_TBL 
(
    CTPVSGG_ID CHAR(8), 
    CARBON_HEAT_JAN INT, 
    CARBON_HEAT_FEB INT, 
    CARBON_HEAT_MAR INT, 
    CARBON_HEAT_APR INT, 
    CARBON_HEAT_MAY INT, 
    CARBON_HEAT_JUN INT, 
    CARBON_HEAT_JUL INT, 
    CARBON_HEAT_AUG INT, 
    CARBON_HEAT_SEP INT, 
    CARBON_HEAT_OCT INT, 
    CARBON_HEAT_NOV INT, 
    CARBON_HEAT_DEC INT, 
    CARBON_HEAT_TOT INT
);

--------------------------------------------------------
--  DDL for Table CARBON_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CARBON_TBL 
(
    CTPVSGG_ID CHAR(8), 
    REGION_NO INT, 
    CARBON_ROAD_TCO2 INT, 
    CARBON_TREE_TCO2 INT, 
    CARBON_YEAR INT DEFAULT 2024
);

--------------------------------------------------------
--  DDL for Table CART_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CART_TBL 
(
    CART_NO INT, 
    MEMBER_ID VARCHAR(20), 
    MARKET_NO INT, 
    QUANTITY INT, 
    ADDED_AT DATETIME
);

--------------------------------------------------------
--  DDL for Table CO2_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CO2_TBL 
(
    C_NO INT, 
    BOARD_NO INT, 
    MEMBER_ID VARCHAR(20), 
    CTPVSGG_ID CHAR(8), 
    C_ELE_A INT DEFAULT 0, 
    C_ELE INT DEFAULT 0, 
    C_GAS_A INT DEFAULT 0, 
    C_GAS INT DEFAULT 0, 
    C_WATER_A INT DEFAULT 0, 
    C_WATER INT DEFAULT 0, 
    C_ROAD_A INT DEFAULT 0, 
    C_ROAD INT DEFAULT 0, 
    C_WASTE_A INT DEFAULT 0, 
    C_WASTE INT DEFAULT 0, 
    C_TOTAL INT DEFAULT 0
);

--------------------------------------------------------
--  DDL for Table CREATE_CAMPAIGN_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CREATE_CAMPAIGN_TBL 
(
    CAMPAIGN_NO INT, 
    CAMPAIGN_TITLE VARCHAR(1000), 
    CAMPAIGN_EXPLANATION VARCHAR(2000), 
    CAMPAIGN_STATUS INT, 
    CAMPAIGN_GOAL_MEMBER INT, 
    CAMPAIGN_EXPIRE_DATE DATETIME, 
    MEMBER_ID VARCHAR(20), 
    CAMPAIGN_START_DATE DATETIME
);

--------------------------------------------------------
--  DDL for Table CTPVSGG_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.CTPVSGG_TBL 
(
    CTPVSGG_ID CHAR(8), 
    CTPV_CD INT, 
    SGG_CD INT, 
    CTPV_NM VARCHAR(50), 
    SGG_NM VARCHAR(50)
);

--------------------------------------------------------
--  DDL for Table DONATION_GROUP
--------------------------------------------------------
CREATE TABLE TEAM1_DB.DONATION_GROUP 
(
    GROUP_ID VARCHAR(50), 
    GROUP_NAME VARCHAR(100), 
    GROUP_DESC VARCHAR(500), 
    GROUP_IMG VARCHAR(200), 
    CATEGORY VARCHAR(50), 
    TOTAL_POINTS INT DEFAULT 0, 
    VIRTUAL_ACCOUNT VARCHAR(50)
);

--------------------------------------------------------
--  DDL for Table FAQ_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.FAQ_TBL 
(
    FAQ_NO INT, 
    FAQ_TITLE VARCHAR(200), 
    FAQ_CONTENT VARCHAR(600), 
    FAQ_CATEGORY VARCHAR(50)
);

--------------------------------------------------------
--  DDL for Table KEYWORD_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.KEYWORD_TBL 
(
    KEYWORD_NO INT, 
    KEYWORD VARCHAR(100), 
    KEYWORD_CATEGORY VARCHAR(50)
);

--------------------------------------------------------
--  DDL for Table MEMBER_LOG_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_LOG_TBL 
(
    MEMBER_LOG_NO INT, 
    MEMBER_ID VARCHAR(20), 
    LOG_IP VARCHAR(30), 
    LOG_TIME DATETIME DEFAULT CURRENT_TIMESTAMP, 
    LOG_ACTION VARCHAR(20), 
    LOG_DETAIL VARCHAR(80), 
    LOG_DEVICE VARCHAR(200), 
    LOG_LOCATION VARCHAR(100), 
    LOG_RESULT INT, 
    LOG_ALERT VARCHAR(50)
);

--------------------------------------------------------
--  DDL for Table MEMBER_MISSION_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_MISSION_TBL 
(
    USER_MISSION_NO INT, 
    MISSION_NO INT, 
    MEMBER_ID VARCHAR(20), 
    COMPLETED_YMD DATE DEFAULT (CURRENT_DATE), 
    CERT_IMAGE_URL VARCHAR(255), 
    ASSIGNED_YMD DATE DEFAULT (CURRENT_DATE)
);

--------------------------------------------------------
--  DDL for Table MEMBER_POINT_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_POINT_TBL 
(
    MEMBER_ID VARCHAR(20), 
    TOTAL_POINT INT DEFAULT 0
);

--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_TBL 
(
    MEMBER_ID VARCHAR(20), 
    MEMBER_PW CHAR(60), 
    MEMBER_NAME VARCHAR(30), 
    MEMBER_GRADE INT DEFAULT 2, 
    MEMBER_EMAIL VARCHAR(30), 
    MEMBER_THUMB VARCHAR(300), 
    ENROLL_DATE DATETIME, 
    MEMBER_STATUS INT, 
    MANNER_SCORE INT, 
    TRADE_COUNT INT, 
    MEMBER_NICKNAME VARCHAR(100)
);

--------------------------------------------------------
--  DDL for Table MEMBER_TBL1
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_TBL1 
(
    MEMBER_ID VARCHAR(20), 
    MEMBER_PW CHAR(60), 
    MEMBER_NAME VARCHAR(30), 
    MEMBER_GRADE INT, 
    MEMBER_NICKNAME VARCHAR(100), 
    MEMBER_EMAIL VARCHAR(30), 
    MEMBER_THUMB VARCHAR(300), 
    ENROLL_DATE DATETIME, 
    MEMBER_STATUS INT, 
    MANNER_SCORE INT, 
    TRADE_COUNT INT, 
    MEMBER_TOTAL_POINT INT, 
    LOCK_UNTIL DATETIME, 
    MEMBER_CO2 INT DEFAULT 0, 
    LOCK_REASON VARCHAR(600)
);

--------------------------------------------------------
--  DDL for Table MEMBER_TBL2
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MEMBER_TBL2 
(
    MEMBER_ID VARCHAR(20), 
    MEMBER_PW CHAR(60), 
    MEMBER_NAME VARCHAR(30), 
    MEMBER_GRADE INT, 
    MEMBER_EMAIL VARCHAR(30), 
    MEMBER_THUMB VARCHAR(300), 
    ENROLL_DATE DATETIME, 
    MEMBER_STATUS INT, 
    MANNER_SCORE INT, 
    TRADE_COUNT INT, 
    MEMBER_NICKNAME VARCHAR(30)
);

--------------------------------------------------------
--  DDL for Table MISSION_TBL
--------------------------------------------------------
CREATE TABLE TEAM1_DB.MISSION_TBL 
(
    MISSION_NO INT, 
    MISSION_TITLE VARCHAR(300), 
    REWARD_POINT INT, 
    MISSION_IMAGE_URL VARCHAR(255), 
    MISSION_TYPE VARCHAR(20), 
    VALIDATION_LABEL VARCHAR(100), 
    VALIDATION_PROMPT VARCHAR(1000)
);