# \uBE44\uBC00 \uD30C\uC77C\uC744 \uBD88\uB7EC\uC624\uB418, \uD30C\uC77C\uC774 \uC5C6\uC5B4\uB3C4 \uC5D0\uB7EC\uB97C \uB0B4\uC9C0 \uB9C8\uB77C
spring.config.import=optional:application-secret.properties
gemini.api.key=AQ.Ab8RN6Kpv8EmQ_u4TJHa9QVoZCqnbUPzNWZagsxteeK-cMpnyQ